/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MusicFun API
 * API for learning. Create your own analogue of a popular music service, such as SoundCloud or Spotify.

<h4>mp3 examples:</h4> 
🔈: https://musicfun.it-incubator.app/api/samurai-way-soundtrack.mp3   
🔈: https://musicfun.it-incubator.app/api/samurai-way-soundtrack-instrumental.mp3
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ArtistsControllerSearchArtistParams,
  CreateArtistRequestPayload,
  GetArtistOutput,
} from '../musicfun.schemas'

import { customInstance } from '.././custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a new artist
 */
export const artistsControllerCreateArtist = (
  createArtistRequestPayload: CreateArtistRequestPayload,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetArtistOutput>(
    {
      url: `/artists`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createArtistRequestPayload,
      signal,
    },
    options,
  )
}

export const getArtistsControllerCreateArtistMutationOptions = <
  TError = null | null | null | null,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof artistsControllerCreateArtist>>,
    TError,
    { data: CreateArtistRequestPayload },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof artistsControllerCreateArtist>>,
  TError,
  { data: CreateArtistRequestPayload },
  TContext
> => {
  const mutationKey = ['artistsControllerCreateArtist']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof artistsControllerCreateArtist>>,
    { data: CreateArtistRequestPayload }
  > = (props) => {
    const { data } = props ?? {}

    return artistsControllerCreateArtist(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ArtistsControllerCreateArtistMutationResult = NonNullable<
  Awaited<ReturnType<typeof artistsControllerCreateArtist>>
>
export type ArtistsControllerCreateArtistMutationBody = CreateArtistRequestPayload
export type ArtistsControllerCreateArtistMutationError = null | null | null | null

/**
 * @summary Create a new artist
 */
export const useArtistsControllerCreateArtist = <TError = null | null | null | null, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof artistsControllerCreateArtist>>,
      TError,
      { data: CreateArtistRequestPayload },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof artistsControllerCreateArtist>>,
  TError,
  { data: CreateArtistRequestPayload },
  TContext
> => {
  const mutationOptions = getArtistsControllerCreateArtistMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * @summary Search artists by substring
 */
export const artistsControllerSearchArtist = (
  params: ArtistsControllerSearchArtistParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetArtistOutput[]>({ url: `/artists/search`, method: 'GET', params, signal }, options)
}

export const getArtistsControllerSearchArtistQueryKey = (params?: ArtistsControllerSearchArtistParams) => {
  return [`/artists/search`, ...(params ? [params] : [])] as const
}

export const getArtistsControllerSearchArtistQueryOptions = <
  TData = Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
  TError = unknown,
>(
  params: ArtistsControllerSearchArtistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerSearchArtist>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getArtistsControllerSearchArtistQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof artistsControllerSearchArtist>>> = ({ signal }) =>
    artistsControllerSearchArtist(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArtistsControllerSearchArtistQueryResult = NonNullable<
  Awaited<ReturnType<typeof artistsControllerSearchArtist>>
>
export type ArtistsControllerSearchArtistQueryError = unknown

export function useArtistsControllerSearchArtist<
  TData = Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
  TError = unknown,
>(
  params: ArtistsControllerSearchArtistParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerSearchArtist>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerSearchArtist>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerSearchArtist<
  TData = Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
  TError = unknown,
>(
  params: ArtistsControllerSearchArtistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerSearchArtist>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerSearchArtist>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerSearchArtist<
  TData = Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
  TError = unknown,
>(
  params: ArtistsControllerSearchArtistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerSearchArtist>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search artists by substring
 */

export function useArtistsControllerSearchArtist<
  TData = Awaited<ReturnType<typeof artistsControllerSearchArtist>>,
  TError = unknown,
>(
  params: ArtistsControllerSearchArtistParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerSearchArtist>>, TError, TData>>
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getArtistsControllerSearchArtistQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Delete an artist by ID
 */
export const artistsControllerDeleteArtist = (id: string, options?: SecondParameter<typeof customInstance>) => {
  return customInstance<null>({ url: `/artists/${id}`, method: 'DELETE' }, options)
}

export const getArtistsControllerDeleteArtistMutationOptions = <TError = null | null, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof artistsControllerDeleteArtist>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<Awaited<ReturnType<typeof artistsControllerDeleteArtist>>, TError, { id: string }, TContext> => {
  const mutationKey = ['artistsControllerDeleteArtist']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof artistsControllerDeleteArtist>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {}

    return artistsControllerDeleteArtist(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ArtistsControllerDeleteArtistMutationResult = NonNullable<
  Awaited<ReturnType<typeof artistsControllerDeleteArtist>>
>

export type ArtistsControllerDeleteArtistMutationError = null | null

/**
 * @summary Delete an artist by ID
 */
export const useArtistsControllerDeleteArtist = <TError = null | null, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof artistsControllerDeleteArtist>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof artistsControllerDeleteArtist>>, TError, { id: string }, TContext> => {
  const mutationOptions = getArtistsControllerDeleteArtistMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
